import { Box } from "@mui/material"
import { useEffect } from "react"

//This is a sample component. Do not edit this file
const SampleComponent = ({text}) =>
{
    useEffect(() => {
        let background = document.getElementById("sample-component-box");
        let textContent = document.getElementById("text-content");

        textContent.style.opacity = '0';
        background.animate([
            {background: 'linear-gradient(45deg, rgba(255,157,43,0.7959558823529411) 0%, rgba(147,0,0,1) 100%)', opacity: '0'},
            {background: 'linear-gradient(45deg, rgba(255,157,43,0.7959558823529411) 0%, rgba(147,0,0,1) 100%)', opacity: '1'}
        ], {duration: 5000});
        textContent.animate([
            {opacity: '0'},
            {opacity: '1'}
        ], {duration: 100, delay: 2000}).onfinish = () => {
            textContent.removeAttribute('style');

            let introEffect = async () => {
                let textBox = document.getElementById("text-content");

                textBox.textContent = ' '.repeat(text.length);
                let charEffect = async (char, index) =>
                {
                    for(let i = 0; i < Math.random() * (100 - 20) + 20; i++)
                    {
                        textBox.textContent = textBox.textContent.slice(0, index) + GenerateChar() + textBox.textContent.slice(index + 1, textBox.textContent.length);
                        await new Promise(r => setTimeout(r, 50));
                    }
                    textBox.textContent = textBox.textContent.slice(0, index) + char + textBox.textContent.slice(index + 1, textBox.textContent.length);
                }

                for(let i = 0; i < textBox.textContent.length; i++)
                {
                    charEffect(text.charAt(i), i);
                }
            }
            introEffect();
        }
    });

    const GenerateChar = () =>
    {
        let charTable = "0123456789abcdefghijklmnopqrstuvwxyz";
        return charTable.charAt(Math.random() * charTable.length);
    }

    return(
        <Box id='sample-component-box' component='div' sx={{width: '100%', height: '100%', background: 'linear-gradient(45deg, rgba(255,157,43,0.7959558823529411) 0%, rgba(147,0,0,1) 100%)', fontSize: '5rem', display: 'flex', justifyContent: 'center', alignItems: 'center'}}>
            <Box id='text-content' component='div'/>
        </Box>
    );
}

export default SampleComponent;